### ISSUE TITLE
Text doesn't render correctly when the inner window size is too small

### ISSUE THREAD

**Issue by geom3trik** [femtovg/femtovg#10]
If the inner window size is set too small text either renders incorrectly or completely dissapears. For example, on the Demo example, setting the height to 500 causes some characters to dissapear, like lowercase 'e', and setting the height to 400 causes all text to dissapear. The same is true for width but not with the same values.

**Comment by adamnemecek** [comment]
@geom3trik thanks for reporting this. want to take a stab at fixing it?

**Comment by geom3trik** [comment]
I can give it a go but I'm not really sure how to even go about debugging this. Have you got any ideas what might be causing it?

**Comment by adamnemecek** [comment]
What os are you using? There are some debuggers for opengl like nvidia nsight or renderdoc.

**Comment by geom3trik** [comment]
I am on windows. I'll give it a go but this is a bit out of my area.

**Comment by adamnemecek** [comment]
I'll take a peek in a bit, there is a bunch of stuff I need to fix and I'll batch it together.
