### ISSUE TITLE
fill_text fills glyph box rather than glyph with sdl2

### ISSUE THREAD

**Issue by KenyC** [femtovg/femtovg#102]
Thanks for the amazing port! I've been using it for a personal project that uses sdl2 (v0.35.1). Everything (rounded boxes, lines, fill, strokes, transforms) works as expected, except text. When trying to use ``fill_text``, the entire glyph box is filled. Below is a minimal example:

```rust
extern crate sdl2;

use sdl2::event::Event;
use sdl2::keyboard::Scancode;

use femtovg::{renderer::OpenGl, Canvas, Color, Paint};


const WIDTH:  u32 = 400;
const HEIGHT: u32 = 300;

fn main() {
    let sdl_context = sdl2::init().expect("Couldn't init SDL2");
    let video_subsystem = sdl_context.video().expect("Couldn't init video");
    let (_, dpi_factor, _) = video_subsystem.display_dpi(0).expect("Can't get a dpi");
  
    let window = video_subsystem
                       .window("Test", WIDTH, HEIGHT)
                       .opengl()
                       .build()
                       .unwrap();

    let _gl_context = window.gl_create_context().unwrap();
    let renderer = unsafe{OpenGl::new_from_function(|string| video_subsystem.gl_get_proc_address(string).cast())}.expect("Cannot create renderer");


    let mut canvas = Canvas::new(renderer).expect("Cannot create canvas");

    let font_id = 
        canvas
            .add_font("examples/assets/Roboto-Bold.ttf")
            .expect("Cannot add font");

    let mut event_pump = sdl_context.event_pump().unwrap();
    'main : loop {

        for event in event_pump.poll_iter() {
            match event {
                Event::Quit {..} |
                Event::KeyDown { scancode: Some(Scancode::Escape), .. } => {
                    break 'main
                },
                _ => (),
            }

        }

        canvas.set_size(WIDTH, HEIGHT, dpi_factor as f32);
        canvas.clear_rect(0, 0, WIDTH as u32, HEIGHT as u32, Color::white());

        let mut paint = Paint::color(Color::black());
        paint.set_font(&[font_id]);
        let _ = canvas.fill_text(
            (WIDTH  as f32)/ 2.0, (HEIGHT as f32)/ 2.0,
            "Hello world!", paint,
        );
        let _ = canvas.stroke_text(
            (WIDTH  as f32)/ 2.0, (HEIGHT as f32)/ 2.0 + 20.,
            "Hello world!", paint,
        );

        canvas.flush();
        window.gl_swap_window();
    }
}
```
Which results in:

![image](https://user-images.githubusercontent.com/25666866/179067332-a536d342-371e-4933-af7e-653e7ff0332e.png)

``stroke_text``gives the expected result. ``fill_text``, on the other hand, fills the entire glyph box.

**Remarks:**
  - Because of #89, I've been using commit de0f9d65 (release v0.3.0). I haven't tried later commits.
  - The text.rs example in the repo (which uses glutin) builds and runs as expected.

Any idea why things break with sdl2?

**Comment by geom3trik** [comment]
I just tried this myself and your example works fine on my machine running Windows for both current femtovg and for the commit you're using. 

![image](https://user-images.githubusercontent.com/9365407/179206882-134afd87-c731-49bf-b948-449bcb9dff72.png)

I'm sorry this probably doesn't help but it might point to the problem being something Linux specific. My first thought was maye something to do with the opengl configuration, is there a way to configure transparency with SDL opengl?

**Comment by KenyC** [comment]
Indeed ! OpenGL configuration was at fault. I finally got it to work by explicitly setting "stencil_size" to 1 and "context_profile" to Core. Concretely, the following two lines after `video_subsystem` initialization:

```rust
video_subsystem.gl_attr().set_stencil_size(1);
video_subsystem.gl_attr().set_context_profile(sdl2::video::GLProfile::Core);
```
This isn't a problem with femtovg, so I'll close. Thanks for your help!
