### ISSUE TITLE
Expose function on `OpenGl` struct to allow passing a glow context.

### ISSUE THREAD

**Issue by DexterHill0** [femtovg/femtovg#108]
I'm creating a gui with `egui` and `eframe`. The `egui` context allows you to get a reference to a `glow` context, which is exactly what the `OpenGl` struct stores. However, there isn't a public function that allows you to instance the `OpenGl` struct straight from a glow context. I don't see any possible way to convert from a glow to glutin context, and even if there was, it's counterintuitive as the glutin context is converted back to a glow context anyway.
Is there any possibility of a function like this being added?

**Comment by tronical** [comment]
Hm the femtovg renderer is consumed by the femtovg canvas, so a borrowed glow context sounds tricky. Would it perhaps be possible for egui to provide/expose a get_proc_address function? Then you could use that with femtovg (marked unsafe but hey.. :)

**Comment by DexterHill0** [comment]
> a borrowed glow context sounds tricky

I say "borrowed" but I should have clarified that it's just referenced counted. So it's actually just `Rc<glow::Context>` which is exactly what's stored in the struct. As long as the glow context is not used internally anywhere else in egui (which I would need to check), moving it into the struct wouldn't cause any other issues then would it?

**Comment by tronical** [comment]
Ahh yes. I guess Arc, not Rc? So the OpenGL renderer would get a new constructor that takes an arc of the glow context.

That said, in an application context like in https://github.com/emilk/egui/blob/master/egui_glow/examples/pure_glow.rs it would seem that you can still access the glutin context - so you could create the femtovg renderer and canvas once. As long as you make sure to only call it when the glutin context is current, I think multiple instances of the glow wrapper should be able to co-exist?

**Comment by DexterHill0** [comment]
> I guess Arc, not Rc?

`Rc`. At least in [`eframe::CreationContext`](https://docs.rs/eframe/latest/eframe/struct.CreationContext.html)

> That said, in an application context like in https://github.com/emilk/egui/blob/master/egui_glow/examples/pure_glow.rs it would seem that you can still access the glutin context - so you could create the femtovg renderer and canvas once.

In an example like that, yeah that would be possible as it's using glutin as the renderer and egui purely for the gui. However, I'm using `eframe` along with `egui` which means I can only get the glow context. I'm not locked into `eframe` so I could switch, it's just simpler and removes a lot of boilerplate.

**Comment by tronical** [comment]
You’re right, in the current release the public API uses Rc. However it seems that the next release will break that and switch to Arc: https://github.com/emilk/egui/commit/b2510676b9a7b45b38820da326e27c05b7b2d408

So if we choose Rc now we’ll have to change to Arc (breaking), and if we go for Arc it means waiting for the new release.

My feeling is that perhaps it’s better if eframe exposed also a loader function so that users can use their own GL wrappers. By providing a loader function they’ll also be able for example to integrate with Skia (where you need a loader fn for a GrDirectContext). Another example is that a loader function allows for gstreamer gl integration.

**Comment by DexterHill0** [comment]
Fair enough, didn't know they were going to switch to Arc. Makes sense for thread saftey I guess though.

In that case I'll open an issue on eframe to see if that's something that can be added for another release.  Thanks!

**Comment by tronical** [comment]
I had another idea: This could perhaps be implemented by means of generalizing and storing a T that derefs to the glow context. Then it doesn’t matter if it’s Rc, Arc or a context itself.
