### ISSUE TITLE
Render quality and performance regression on v0.4.0

### ISSUE THREAD

**Issue by aakamenov** [femtovg/femtovg#145]
I just updated my femtovg renderer to the new v0.4.0 from v0.3.7 and immediately noticed that everything became very blurry.
So I tried running the demo in this repo on 98ffbf8988bc07985c8852cc466eb3f59e91a464 and 4b857cc64142529203a55f24fb6fc531c2523277 and noticed the same regression. Here's the screenshots for comparison - it's especially obvious when looking at the text:

v0.3.7                      |  v0.4.0
:-------------------------:|:-------------------------:
![v037](https://user-images.githubusercontent.com/29430447/216822632-126932d3-1423-44a8-9e51-7b221ffee9be.png) | ![v04](https://user-images.githubusercontent.com/29430447/216822649-273b5c4c-74a3-4b15-98bb-fd14b181156e.png)

You'll also notice that the FPS dropped from a 1000 to 60 on the new version. I didn't see any framerate caps in the demo code but maybe it's implemented in the library itself? So what could be causing these issues?

I tested this on Linux 6.1.9-arch1-1. Haven't tried Windows or MacOS.

**Comment by tronical** [comment]
Hm. This could be caused by the new glutin setup code that ends up with a vsync context and maybe somehow multi sampling.

**Comment by tronical** [comment]
@aakamenov Could you try and see if this patches fixes the issue for you?

```patch
diff --git a/examples/helpers/mod.rs b/examples/helpers/mod.rs
index d5d102a..d728462 100644
--- a/examples/helpers/mod.rs
+++ b/examples/helpers/mod.rs
@@ -54,7 +54,7 @@ pub fn start(
                         let transparency_check = config.supports_transparency().unwrap_or(false)
                             & !accum.supports_transparency().unwrap_or(false);

-                        if transparency_check || config.num_samples() > accum.num_samples() {
+                        if transparency_check || config.num_samples() < accum.num_samples() {
                             config
                         } else {
                             accum
```

**Comment by aakamenov** [comment]
Yes, can confirm that fixed it! Seems counter-intuitive to me but it will be reading exercise for me to find out why it works.

**Comment by tronical** [comment]
👍 Thanks for checking. I've pushed that fix to the master branch.
