### ISSUE TITLE
Inter font is rendered incorrectly

### ISSUE THREAD

**Issue by WilliamVenner** [femtovg/femtovg#183]
Hi, I noticed that some characters from the Inter font are rendered incorrectly.

https://fonts.google.com/specimen/Inter

![image](https://github.com/femtovg/femtovg/assets/14863743/e64c4672-bc27-4634-a0a8-b0456e910f78)

Some things to note:

- Characters `f`, `e`, `t` and `4` are rendered incorrectly (and more, I would imagine)
- It's a very popular font, so I do not think the font itself is at fault.
- Happens at any font size.
- The gaps get larger when a bolder variant of the font is chosen.
- Turning on/off anti-aliasing has no effect.
- I'm on Windows 11.
- Happens on macOS too it seems.

## Reproduction

1. Drop [`Inter-Medium.ttf`](https://fonts.google.com/specimen/Inter) into `examples/assets/`
2. In `examples/text.rs`, append `0123456789` to the `The quick brown fox jumps over the lazy dog` string
3. In `examples/text.rs`, change the `sans` font from `Roboto-Medium.ttf` to `Inter-Medium.ttf`.
4. `cargo run --example text`

**Comment by tronical** [comment]
Ack. Seen this effect with various fonts and paths. I’m most curious what causes it, but I don’t know enough about the path code :(

**Comment by WilliamVenner** [comment]
@CryZe said:

> what's happening here is that it uses the wrong fill rule. It's probably even odd instead of winding
> So paths overlapping causes it to mess up
> it seems like you can specify it somewhere: https://docs.rs/femtovg/0.7.1/femtovg/enum.FillRule.html
> there's no winding though

**Comment by lylythechosenone** [comment]
Is anybody working on this? It's a quite significant bug that's currently turning me to skia instead.
