### ISSUE TITLE
Dependency `generational-arena` is unmaintained

### ISSUE THREAD

**Issue by rjzak** [femtovg/femtovg#198]
`generational-arena` was archived November 2023. https://github.com/fitzgen/generational-arena

https://rustsec.org/advisories/RUSTSEC-2024-0014.html

**Comment by tronical** [comment]
ACK. Might make sense to switch to slotmap instead. One issue is that sadly generational-arena is part of the public API here: https://docs.rs/femtovg/latest/femtovg/struct.ImageId.html

But I doubt that changing this will cause much breakage - would require a major version bump though.
