### ISSUE TITLE
Linear gradients render incorrectly on NVIDIA/Linux

### ISSUE THREAD

**Issue by iamralpht** [femtovg/femtovg#2]
I noticed that linear gradients aren't rendered correctly on NVIDIA on Linux (but Intel graphics on Linux works fine). I believe the problem is because the linear case uses extents for the signed distance round-rect function in the fragment shader which are on the edge of `mediump`'s precision, causing an unexpectedly lumpy interpolation.

If I use `highp` precision in the fragment shader, then NVIDIA renders as expected (and the same as Intel).

**Comment by adamnemecek** [comment]
Do you want to make a pull request?

**Comment by iamralpht** [comment]
Yep, just writing the commit message ;)
