### ISSUE TITLE
Verbs visibility issue

### ISSUE THREAD

**Issue by Drewol** [femtovg/femtovg#203]
[Path::verbs](https://docs.rs/femtovg/latest/femtovg/struct.Path.html#method.verbs) is public but the Verb type is not public so you can't actually do anything with the verbs iterator(?)

**Comment by tronical** [comment]
Sounds reasonable. PRs welcome :)

**Comment by Drewol** [comment]
Should the verbs type be visible or should the Path::verbs function not be public?

**Comment by tronical** [comment]
I think the verbs type public as well as PathIter is okay.
