### ISSUE TITLE
How to do animations triggered by events?

### ISSUE THREAD

**Issue by Frankkkkk** [femtovg/femtovg#207]
Hello,

First of all, thank you for this nice lib.
I'm trying to figure out how best to do animations triggered by an event (scroll wheel, button, etc..)

Basically, I'm trying to recreate something like [this](https://youtu.be/7QaPdoh1v4Y?si=YrbYYItkNryCjWVj&t=22). It is a contextual menu where its state is triggered by events. However, each change of state is associated with an event.

Is there a clever way to represent this in a nice idiomatic way?

Many thanks!
Cheers

**Comment by porky11** [comment]
This is a vector graphics library.
If you want animations, you just have to render different things in different frames.
