### ISSUE TITLE
Grammatical Arabic errors in the text example

### ISSUE THREAD

**Issue by alliby** [femtovg/femtovg#210]
There are some grammatical errors and spelling mistakes in the Arabic text used in the `text.rs` example.
 - The word "ساهلة" (sahilah) is misspelled. The correct spelling is "سهلة" (sahlah), meaning "easy" or "simple".
 - also for the word "جاذبة" (jadhhibah). the correct spelling is "جذابة" (jadhdhibah), meaning "attractive" or "appealing".
 - and for the word "الحوف" (al-hawf) is incorrect word. and following the context the correct word is "الحروف" (al-huruf), meaning "letters" or "characters".

**Comment by rhelmot** [comment]
I've opened pull request #211 with the appropriate substitutions. Can you double check that it's correct now?

**Comment by alliby** [comment]
Yes, the substitutions are correct.

**Comment by rhelmot** [comment]
Thank you so much! It's sad we don't have anyone who knows any RTL languages on the femtovg team so we could assemble an example of RTL text that we could actually verify correct, but now it's fixed :)
