### ISSUE TITLE
Transform2D::new shouldn't take a mutable self reference

### ISSUE THREAD

**Issue by porky11** [femtovg/femtovg#214]
Will probably fix this tomorrow.

It obviously shouldn't take a mutable reference since it isn't even used.
But it's still a breaking change.

While looking at it, I realized the other methods are also confusing. When a method is called `translate`, I expect it to translate it even further instead of setting the translation absolute.
Maybe these should be called `set_scale` and `set_translation` instead, and `scale` and `translate` will do relative transforms.

Or myabe it's best to start using some external math library? I think there has been the plan to switch to euclid for a while now.

**Comment by tronical** [comment]
Worth fixing new() IMO
