### ISSUE TITLE
How to Properly Create a Canvas in femtovg for Drawing Images Based on Configuration?

### ISSUE THREAD

**Issue by iDestin** [femtovg/femtovg#219]
### Issue Description

Hello

I am trying to use the `femtovg` library to generate images based on a configuration. I would like to understand the correct way to create a `Canvas` using `femtovg`.

Specifically, I want to know how to properly create a `Canvas` so that I can draw shapes according to a predefined configuration and generate the final image.

```rust
use femtovg::Canvas;

fn main(){
  // I don't know what renderer is this
  let &mut canvas = Canvas::new(renderer);
}
```

### Expected Assistance
* How can I correctly create a Canvas to enable drawing?
* Any basic example code for drawing shapes would be greatly appreciated.

**Thank you very much for your help!**

**Comment by porky11** [comment]
Why would you ever do `let &mut ... = ...`?
Maybe you should learn the basics of Rust first.

If you don't understand how it works, just start by copying one of the examples.

Also feel free to use some template which I use for most of my programs: https://gitlab.com/porky11/gapp-template
It already creates the canvas and uses some wrapper lib.

**Comment by iDestin** [comment]
> Why would you ever do `let &mut ... = ...`? Maybe you should learn the basics of Rust first.
> 
> If you don't understand how it works, just start by copying one of the examples.
> 
> Also feel free to use some template which I use for most of my programs: https://gitlab.com/porky11/gapp-template It already creates the canvas and uses some wrapper lib.

Yes, I'm learning Rust, but it's really difficult😂. Thank you so much
