### ISSUE TITLE
WGPU Renderer crashes without call to `set_size` every frame.

### ISSUE THREAD

**Issue by Drewol** [femtovg/femtovg#226]
Actually the crash is caused by there not being any `SetRenderTarget` command but the easiest way to set this seems to be with `set_size`. 

Crashes here https://github.com/femtovg/femtovg/blob/master/src/renderer/wgpu.rs#L1592 due to `rpass` being `None`.

**Comment by Drewol** [comment]
It crashes on `flush_to_surface` when there's no call to `set_size`.  `set_size` creates a `SetRenderTarget` command (which maybe it shouldn't?) and flushing requires a `SetRenderTarget` because from what I can see that's the only place where `render_pass_builder.rpass` is initialized.

**Comment by tronical** [comment]
Right, it should suffice to call it just once and we should have an initial pass always ready.
