### ISSUE TITLE
WGPU renderer should maybe not submit to queue

### ISSUE THREAD

**Issue by Drewol** [femtovg/femtovg#227]
Im building a game where femtovg is just one part of the whole frame and when measuring performance i noticed that a lot of time was spent submitting the WGPU commands.

The wgpu-rs wiki states that submits should be kept to a minimum. https://github.com/gfx-rs/wgpu/wiki/Do%27s-and-Dont%27s#dont-submit-many-times-per-frame 

So instead I think the render function should return the commands or take a render pass or encoder as an input. The render pass option is probably not realistic due to the complexity of femtovg. Potential places of inspiration could be the egui wgpu renderer.

**Comment by tronical** [comment]
Returning an (opaque) CommandBuffer might be possible, but it requires some trickery to fit this into the Canvas API. Maybe an associated type on the Renderer interface.

**Comment by Drewol** [comment]
Yeah that's what I did in a branch to verify the performance improvements. Though that branch also has a few other things for my own testing so unfortunately I can't make a neat PR from that. https://github.com/Drewol/femtovg/commit/5e9bd9ee18edc3ebe5cf046015cf859ae062558a
