### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [femtovg/femtovg#36]
Hi, I am interested in using your crate but I have some questions:

1. What is the license of this crate? Is it MIT, GPL etc?
2. Is it similar to using something like [Processing](https://processing.org/)? Can I please get a basic example if possible of where I can get started?
3. How well maintained is this project?
4. Is it Alpha, Beta, or Stable this project?
5. Can I display stuff on the Wayland display?
6. Can I use it to create a taskbar similar to [Polybar](https://polybar.github.io/)?
7. Can I use it to create my own widgets, something that looks like these:

![Desktop](https://user-images.githubusercontent.com/34926497/114296683-f8fb1d80-9aef-11eb-85f0-874cfa5bfd4f.png)
![Desktop](https://user-images.githubusercontent.com/34926497/114296709-116b3800-9af0-11eb-9b35-444e6a680304.png)
8. Is there any man pages/docs available for this crate?

**Comment by peter-todorov** [comment]
Hey Joe, here are some answers:

> 1. What is the license of this crate? Is it MIT, GPL etc?

This crate is dual licenced under MIT and Apache 2 at your option. If you wonder about the licensing of other crates you can almost always find it in the Cargo.toml file.
![DeepinScreenshot_select-area_20210512110113](https://user-images.githubusercontent.com/7164437/117940090-611c6980-b311-11eb-8ec3-867e2f6760aa.png)

> 2. Is it similar to using something like Processing? Can I please get a basic example if possible of where I can get started?

Yes, one could say this crate is a lot like processing, but I would put it closer to something like the HTML canvas API. For example, there's some functionality in Processing that is not present in femtovg and you'll have to pull a different crate and use it with femtovg (eg. noise generation, random numbers).

> 5. Can I display stuff on the Wayland display?

You should be able to, yes. But I haven't tested it.

> 6. Can I use it to create a taskbar similar to Polybar?

I don't know. If you can obtain an OpenGL context you can use this crate.

> 7. Can I use it to create my own widgets, something that looks like these:

Yes, there are multiple people working on UI libraries using femtovg for drawing widgets. Check out the SixtyFPS project - https://github.com/sixtyfpsui/sixtyfps

**Comment by Joe23232** [comment]
Thanks mate :)

**Comment by porky11** [comment]
8. has not been answered:
Answer: https://docs.rs/femtovg

**Comment by Joe23232** [comment]
@porky11 THanks mate
