### ISSUE TITLE
Canvas.width() and Canvas.height() return f32 values.

### ISSUE THREAD

**Issue by birkett83** [femtovg/femtovg#44]
`Canvas.width` and `Canvas.height` are `u32` values. `Canvas.set_size` takes `u32` values. If we're rendering to an image instead of the screen the image sizes appear to be stored as `usize` instead of `u32` for some reason but they're still integer.

Why does `Canvas.width()` convert these to `f32` ? Fractional values don't appear to make any sense here. 

I believe the return types should be changed to `u32`

**Comment by peterprototypes** [comment]
I know it's been two years. @ollpu @tronical @birkett83 are you still ok with this update?

**Comment by tronical** [comment]
Yep (for me at least :)
