### ISSUE TITLE
OpenGl::new is unsound

### ISSUE THREAD

**Issue by TheRawMeatball** [femtovg/femtovg#46]
This function takes an arbitrary function that returns a `*const c_void` and then passes it to a C function. Because it's possible to call this function like this:
```rs
OpenGl::new(|_| 42 as *const c_void);
```
and the fact the C function would happily dereference this address, this function should be marked unsafe.

**Comment by Lemmih** [comment]
Hi @TheRawMeatball. Thanks for pointing out this issue. `OpenGl::new` has been renamed to `OpenGl::new_from_function` and is marked as unsafe. Safe initialization (for glutin) can be done with `OpenGl::new_from_glutin_context`.
