### ISSUE TITLE
SVG example renders incorrectly on macos.

### ISSUE THREAD

**Issue by Lemmih** [femtovg/femtovg#53]
SVG tiger is completely black. Using a 2020 MacBookAir M1.

https://user-images.githubusercontent.com/1443107/137591346-59d303de-0813-4aa1-a9fd-cc6b5b779960.mov

**Comment by tronical** [comment]
This is a regression caused by 94efa91eb68c182d8ddb9ee9141363a0a8ddc33c - another dependency bump (oops!)

**Comment by tronical** [comment]
Thanks for the fix @Lemmih!
