### ISSUE TITLE
Expanded image loading API?

### ISSUE THREAD

**Issue by rhelmot** [femtovg/femtovg#88]
I don't know if my use case for this is valid so I'll describe where I'm at and what I'd like and you can tell me if it seems like a good idea.

I would like to be able to load images in a background thread. Currently, to do this I have to depend on the exact same version of `image`, `rgb`, and `imgref` that femtovg does, and then rely on e.g. the `From<ImgRef<'a, RGBA8>>` impl to get myself a ImageSource, which I can ferry to the main thread and then load into my canvas lazily.

Instead, I would like to just be able to say `femtovg::ImageSource::load_from_rgba_buf(mem, pitch)` and `femtovg::ImageSource::load_from_mem(mem, femtovg::guess_format(mem))` - basically the same api as `image` and `imgref` provide. In fact, it might be best to cut out the middle man and just directly re-export `image` and `imgref` and `rgb`.

Let me know what you think!

**Comment by tronical** [comment]
Interesting idea. Let's discuss :)

Image loading is three things:

1. I/O for getting the encoded image into memory
2. Decoding the image into something that the GPU can consume
3. Uploading the data to the GPU

Ideally all these merge into one, i.e. an image format is used that the GPU can decode natively (like basis) and the GPU can "mmap" the file from disk. But I think the reality will continue to require all three steps for a while.

The step of uploading to the GPU is unfortunately blocking, that's the current `load_image_*` API on the `Canvas` and I think that's hard to delegate to a thread.

The first two steps don't really have to be done inside femtovg. I think crates like rayon make it easier to delegate especially the decoding into worker threads. What happens in the meantime, between deciding to load an image and it being ready for rendering, is a little bit up to the application. Maybe it decides to show a placeholder instead, or not reserve space in the layout for the image until it is ready?

What is the behavior that you are looking for in your application? What have you identified as being "slow" in your scenario?

**Comment by rhelmot** [comment]
Thanks for your careful explanation!

> What is the behavior that you are looking for in your application? What have you identified as being "slow" in your scenario?

I have an enormous number of images I need to decode and have ready in memory before my application can start up. This process takes a couple of seconds. In order to keep the interface responsive during startup, this happens in a background thread while the main thread displays a progress bar. I could _maybe_ do I/O lazily, but I would prefer to not have to e.g. answer questions about what happens if an image is deleted between resource discovery and I/O.

> The first two steps don't really have to be done inside femtovg.

This is the main point I was trying to pry into with my original explanation - while these steps don't have to be done inside femtovg, they need to produce output data with types that femtovg is capable of consuming. To my knowledge, the only way femtovg can consume image data is through the `ImageSource` enum, and the only way to construct an ImageSource is by having an `imgref::ImgRef` or an `image::DynamicImage`. Both of these require dependencies which are not re-exported from femtovg, and thus require users to match exact versions of femtovg's dependencies, which is cumbersome and error-prone. The thing I'm proposing is to either re-export or wrap these dependencies.

**Comment by tronical** [comment]
Ok, let’s look at the data interface first then :)

Right now the rgb crate and the imgref types are used in the public API, along with DynamicImage. I’d say the latter is convenience. The former is I think a crate that has a stable API, so I think conflicts with mismatches are very unlikely.

I think as a minimal interface that’s quite good: Data is provided in defined formats for a short period of time, during which femtovg will make a copy.

We could re-export all of image though.

**Comment by rhelmot** [comment]
Sorry for the delay.

I'm not too familiar with what the conventions of doing things like this in published crates are, but it seems to me that requiring the user to add a dependency in order to use certain api features is something to be avoided, even if it's just making an implicit dependency explicit. If you really think this is okay, I'm fine with just re-exporting image.

**Comment by tronical** [comment]
No worries. Fwiw I’m almost not an expert on conventions here :).

How would a wrapping API look like in your opinion, one that doesn’t require imgref or rgb?

**Comment by rhelmot** [comment]
So I need to be able to get an ImageSource, somehow. Right now my options are into() on either an image::DynamicImage or an imgref::ImgRef. The main use cases that these cover are:

- image::DynamicImage: I would like to use the image crate to decode load an image, probably guessing its format based on magic numbers. The two ways one might want to do this are from a buffer or from a seekable stream.
- imgref::ImgRef: I have some image data already decoded in either rgb8, rgba8, or gray8 format and I would like to push it into femtovg. This data may be a reference to some aligned rectangular subset of a larger buffer.

Based on these use cases, I propose the following wrapping API:

```rust
impl ImageSource {
    pub fn decode_from_buf(buf: &[u8]) -> Result<Self>;
    pub fn decode_from_stream<R: std::io::Read + std::io::Seek>(fp: &mut R) -> Result<Self>;
    pub fn from_rgb8(buf: &[u8], width: usize, height: usize, pitch: usize) -> Result<Self>;
    pub fn from_rgba8(buf: &[u8], width: usize, height: usize, pitch: usize) -> Result<Self>;
    pub fn from_gray8(buf: &[u8], width: usize, height: usize, pitch: usize) -> Result<Self>;
}
```

What do you think? I'm not sure which I like better of re-exporting image/imgref vs this api.

**Comment by ogoffart** [comment]
I believe that imgref is meant to be a lightweight crate used for exactly this purpose of representing a type of an image that can be used across different crates. The advantage of using imgref is that more crate can support that type and  so makes interoperability easier without the need to convert or re-check the sizes.

Maybe femtovg should re-export the imgref crate types, so users don't have to add it to their Cargo.toml. (eg: `pub use imgref;`)

**Comment by rhelmot** [comment]
Any additional thoughts on re-exporting image, rgb, and imgref? Should I make a pull request adding this?

**Comment by tronical** [comment]
I think it’s a good idea:)
