### ISSUE TITLE
Make `femtovg::Paint` only `Clone`, not `Copy`

### ISSUE THREAD

**Issue by tronical** [femtovg/femtovg#93]
On `x86_64-apple-darwin` the size of `femtovg::Paint` is 776 bytes. I'd like to suggest that 

  * we break the API and remove the `Copy` trait
  * Make the implementation lighter by using Rc and copy-on-write. As added benefit we can make the number of gradient stops variable, for example.

Thoughts?

@adamnemecek @geom3trik @ollpu @lemmih @ogoffart ?

**Comment by geom3trik** [comment]
Sorry for the delay in responding but I would be happy with these changes. Having unlimited gradient stops sounds useful but I am curious what, if any, performance impact this would have.

**Comment by tronical** [comment]
Hard to say if there is any impact on performance. Right now a lot of bytes are copied around. At the same time I’m not sure it’s significant. There’ll be less of that but more explicit code to call clone.

**Comment by porky11** [comment]
Yeah, paint being copy felt weird to me anyway.
Not sure about the usage of Rc. Wouldn't normal references be enough?

If there's going to be a breaking change anyway, we might consider changing more about how paint works.
For example removing the transform from the paint and making it an additional parameter, or having special purpose paint for text or outlines, or splitting the special purpose parameters into new structs.
This way, some of the parameters might even be able to stay copy (like the transform).

**Comment by nicoburns** [comment]
I would suggest that the following two things should be done:

- Remove the Copy implementation (copies of such a large struct shouldn't be implicit)
- Update methods taking Paint to take &Paint where possible.

If people want to use `Rc`, then they can easily and cheaply turn an `Rc<Paint>` into an `&Paint` on demand. And this also makes it flexible so if people want to use `Arc` or any other container then they can.

**Comment by porky11** [comment]
@nicoburns I already did this, and it has been merged.
@tronical This issue can be closed now, right?

**Comment by tronical** [comment]
Indeed, thanks. https://github.com/femtovg/femtovg/pull/117 Fixes this
